application: potchreader
version: 0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /template
  static_dir: /template
# upload: /template
# application_readable: yes
  
#- url: /seturl.html  
# static_files: seturl.html
# upload: seturl.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
